# Generated by Django 5.0.4 on 2024-05-10 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_pos', '0002_rename_price_product_price_per_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='date_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
