# Generated by Django 5.0.4 on 2024-05-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_pos', '0003_rename_date_updated_customer_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
